name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: test (Node ${{ matrix.node-version }}, React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14", "16", "18"]
        react-version: ["16", "17", "18"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --global install npm@latest
      - run: npm ci
      - run: npm install --save-dev 'react@${{ matrix.react-version }}' 'react-dom@${{ matrix.react-version }}' '@testing-library/react@12'
        if: ${{ matrix.react-version == '16' || matrix.react-version == '17' }}
      - run: npm test --ignore-scripts
      - run: npm run posttest

  lint:
    uses: ybiquitous/.github/.github/workflows/nodejs-lint-reusable.yml@main
