name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: "test for react ${{ matrix.react-version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        react-version: ["16", "17", "18"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: npm
      - run: npm --global install npm@latest
      - run: npm ci
      - run: npm install --save-dev 'react@${{ matrix.react-version }}' 'react-dom@${{ matrix.react-version }}' '@testing-library/react@12'
        if: ${{ matrix.react-version == '16' || matrix.react-version == '17' }}
      - run: npm test --ignore-scripts
      - run: npm run build

  lint:
    uses: ybiquitous/.github/.github/workflows/nodejs-lint-reusable.yml@main
