name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: test (Node ${{ matrix.node-version }}, React ${{ matrix.react-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12", "14", "16"]
        react-version: ["16", "17"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --global install npm@latest
      - run: npm ci
      - run: npm install 'react@${{ matrix.react-version }}' 'react-test-renderer@${{ matrix.react-version }}'
        if: ${{ matrix.react-version != '17' }}
      - run: npm run lint
      - run: npm test
      - run: npm run release:dry-run
