name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: "test for react ${{ matrix.react-version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        react-version: ["16", "17", "18", "19"]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
      - name: Install latest npm
        run: |
          npm --global install npm@latest
          echo "Installed npm version: $(npm --version)"
      - name: Install dependencies
        run: npm ci
      - name: Install React dependencies
        if: ${{ matrix.react-version != '19' }}
        env:
          REACT_VERSION: ${{ matrix.react-version }}
        run: |
          if [[ $REACT_VERSION =~ ^(16|17) ]]; then
            npm install --save-dev "react@${REACT_VERSION}" "react-dom@${REACT_VERSION}" '@testing-library/react@12'
          else
            npm install --save-dev "react@${REACT_VERSION}" "react-dom@${REACT_VERSION}"
          fi
      - name: Test
        run: npm test --ignore-scripts
      - name: Build
        run: npm run build

  lint:
    uses: ybiquitous/.github/.github/workflows/nodejs-lint-reusable.yml@main
